// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADtePdl6okWFVz1itv2TXduiKrS4zxwgc',
    appId: '1:85310041975:web:c41abce9b4b283c8bc3b72',
    messagingSenderId: '85310041975',
    projectId: 'jobpoint-mobile-app-28123',
    authDomain: 'jobpoint-mobile-app-28123.firebaseapp.com',
    storageBucket: 'jobpoint-mobile-app-28123.appspot.com',
    measurementId: 'G-4SJPYFH0KP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz-7vycw-JHO0_c-YAMCOByyFKfbBd1cU',
    appId: '1:85310041975:android:9dde06f653b1fefbbc3b72',
    messagingSenderId: '85310041975',
    projectId: 'jobpoint-mobile-app-28123',
    storageBucket: 'jobpoint-mobile-app-28123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4Rs70jgug7KP7j4WbhC57Hv3dWzahqiw',
    appId: '1:85310041975:ios:225efc27edeffd5bbc3b72',
    messagingSenderId: '85310041975',
    projectId: 'jobpoint-mobile-app-28123',
    storageBucket: 'jobpoint-mobile-app-28123.appspot.com',
    androidClientId: '85310041975-t1o5ojajl9mde0hi5u1sgshbk1ti9mt5.apps.googleusercontent.com',
    iosClientId: '85310041975-hmo7lutkvjfkb70mapamneli3jj4iihc.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobpoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4Rs70jgug7KP7j4WbhC57Hv3dWzahqiw',
    appId: '1:85310041975:ios:225efc27edeffd5bbc3b72',
    messagingSenderId: '85310041975',
    projectId: 'jobpoint-mobile-app-28123',
    storageBucket: 'jobpoint-mobile-app-28123.appspot.com',
    androidClientId: '85310041975-t1o5ojajl9mde0hi5u1sgshbk1ti9mt5.apps.googleusercontent.com',
    iosClientId: '85310041975-hmo7lutkvjfkb70mapamneli3jj4iihc.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobpoint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADtePdl6okWFVz1itv2TXduiKrS4zxwgc',
    appId: '1:85310041975:web:4f23b430c87116d2bc3b72',
    messagingSenderId: '85310041975',
    projectId: 'jobpoint-mobile-app-28123',
    authDomain: 'jobpoint-mobile-app-28123.firebaseapp.com',
    storageBucket: 'jobpoint-mobile-app-28123.appspot.com',
    measurementId: 'G-B8N8NJJDEY',
  );

}